### ISSUE TITLE
FR: Multiple named sets of remotes 

### ISSUE THREAD

**Issue by qroac** [r-darwish/topgrade#368]
In addition to the default set of remote machines I'd love to see the option, to define named sets of additional remotes.

Reason:
At work I have some machines in different maintenance schedules.  
In addition I install updates on my PC and rasperries at home using the same laptop.
To update machines in multiple scenarios at work and at home with topgrade I currently use different config files, copying the right one in place each time before using topgrade. A not very comfortable process ...

Request:
- new config hasmap remote_topgrade_sets
- new CLI flag -r to define the set to use

In addition to the array notation for remote_topgrades, there could be the option to define remotes as hash table entries. If topgrade is called with the name of a remote set, it executes on this remotes. If not, it runs with the remotes from the default list (if defined).

```toml
remote_topgrades = ["the", "default", "remotes"]

[remote_topgrade_sets]
scheduleset1 = ["first", "to", "be", "updated"]
scheduleset2 = ["second", "set", "of", "machines"]
```

```bash
# Runs local and on default remotes
topgrade
# Runs local and on the first remote set
topgrade -r scheduleset1
```
