### ISSUE TITLE
Support for specific environment variables for each steps

### ISSUE THREAD

**Issue by blackcat-917** [r-darwish/topgrade#719]
Topgrade should support a config entry to add environment variables for each step, this could be useful if a user would like to set a specific compilation flag when compiling from source or to add options to commands without flags.

**Comment by MCOfficer** [comment]
It's not a solution, but you can work around this by adding your upgrade step as a custom command, and specify the environment variable in the command.

```toml
[commands]  
"FooUpdater" = "MYENV=MYVALUE fooupdater -u"

```
